https://towardsdatascience.com/deploying-a-simple-machine-learning-model-into-a-webapp-using-tensorflow-js-3609c297fb04

In [3]:
from tensorflow import keras
import numpy as np
from tensorflow.keras.datasets import mnist
import matplotlib.pyplot as plt
import json
from random import shuffle

In [2]:
!nvidia-smi

Sun Nov 15 12:22:16 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 451.67       Driver Version: 451.67       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8    N/A /  N/A |     75MiB /  4096MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU  

## Load in the dataset       

In [4]:
dataset = []



In [8]:
def add_data(filename):
    path = 'fft_data/'
    with open(path + filename, 'r') as myfile:
        data=myfile.read()

    obj = json.loads(data)


    for fft in obj:
        dataset.append((fft['vowel'], np.array(fft['FFT'], dtype=np.uint8)))

In [9]:
file_names = ["ae_fft_data.txt",
              "ah_fft_data.txt",
              "book_fft_data.txt",
              "ee_fft_data.txt",
              "eh_fft_data.txt",
              "er_fft_data.txt",
              "ih_fft_data.txt",
              "oo_fft_data.txt",
              "uh_fft_data.txt"]

In [10]:
for f in file_names:
    add_data(f)

In [13]:
len(dataset)

4586

In [ ]:
"""
path = 'fft_data'
with open(path + '/ee_fft_data.txt', 'r') as myfile:
    data=myfile.read()

obj = json.loads(data)


for fft in obj:
   dataset.append((fft['vowel'], np.array(fft['FFT'], dtype=np.uint8)))
   """


In [99]:
"""

path = 'fft_data'
with open(path + '/ih_fft_data.txt', 'r') as myfile:
    data=myfile.read()

obj = json.loads(data)


for fft in obj:
   dataset.append((fft['vowel'], np.array(fft['FFT'], dtype=np.uint8)))
   """

In [14]:
shuffle(dataset)

In [15]:
y_dataset = [vowel for vowel, fft in dataset]
x_dataset = [fft for vowel, fft in dataset]

In [16]:
# change to numpy arrays and reshape training data for tf
x_dataset = np.array(x_dataset)
x_dataset = x_dataset.reshape(len(x_dataset),512,1).astype('float32')

y_dataset = np.array(y_dataset).astype('float32')

In [17]:
# split in to train and test
cutoff = round(len(y_dataset)*0.8) # 80/20 split
X_train = x_dataset[:cutoff]
y_train = y_dataset[:cutoff]
X_test = x_dataset[cutoff:]
y_test = y_dataset[cutoff:]

In [19]:
len(x_dataset), len(X_train), len(X_test), len(X_train)+len(X_test)
len(y_dataset), len(y_train), len(y_test), len(y_train)+len(y_test)

(4586, 3669, 917, 4586)

In [21]:
y_test[0]

array([0., 1., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

## Create and Train the Model

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from keras.utils import np_utils

# flatten 28*28 images to a 784 vector for each image
num_pixels = X_train.shape[1] * X_train.shape[2]


X_train = X_train.reshape(X_train.shape[0], num_pixels).astype('float32')
X_test = X_test.reshape(X_test.shape[0], num_pixels).astype('float32')


#X_train = X_train.reshape((X_train.shape[0], 28, 28, 1)).astype('float32')
#X_test = X_test.reshape((X_test.shape[0], 28, 28, 1)).astype('float32')

# normalize inputs from 0-255 to 0-1
X_train = X_train / 255
X_test = X_test / 255

# one hot encode outputs
#y_train = np_utils.to_categorical(y_train)
#y_test = np_utils.to_categorical(y_test)
num_classes = y_test.shape[1]





In [31]:
# https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/
model = Sequential()
model.add(Dense(512, input_dim=512, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(9, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=150, batch_size=10)

Epoch 1/150
367/367 [==============================] - 1s 2ms/step - loss: 0.2046 - accuracy: 0.6446
Epoch 2/150
367/367 [==============================] - 1s 2ms/step - loss: 0.0865 - accuracy: 0.8820
Epoch 3/150
367/367 [==============================] - 1s 2ms/step - loss: 0.0499 - accuracy: 0.9395
Epoch 4/150
367/367 [==============================] - 1s 2ms/step - loss: 0.0340 - accuracy: 0.9621
Epoch 5/150
367/367 [==============================] - 1s 2ms/step - loss: 0.0229 - accuracy: 0.9768
Epoch 6/150
367/367 [==============================] - 1s 2ms/step - loss: 0.0179 - accuracy: 0.9793
Epoch 7/150
367/367 [==============================] - 1s 2ms/step - loss: 0.0159 - accuracy: 0.9836
Epoch 8/150
367/367 [==============================] - 1s 2ms/step - loss: 0.0099 - accuracy: 0.9921
Epoch 9/150
367/367 [==============================] - 1s 2ms/step - loss: 0.0061 - accuracy: 0.9945
Epoch 10/150
367/367 [==============================] - 1s 2ms/step - loss: 0.0081 - accura

367/367 [==============================] - 1s 2ms/step - loss: 1.0090e-05 - accuracy: 1.0000
Epoch 80/150
367/367 [==============================] - 1s 2ms/step - loss: 8.5628e-06 - accuracy: 1.0000
Epoch 81/150
367/367 [==============================] - 1s 2ms/step - loss: 7.5560e-06 - accuracy: 1.0000
Epoch 82/150
367/367 [==============================] - 1s 2ms/step - loss: 6.2934e-06 - accuracy: 1.0000
Epoch 83/150
367/367 [==============================] - 1s 2ms/step - loss: 5.5778e-06 - accuracy: 1.0000
Epoch 84/150
367/367 [==============================] - 1s 2ms/step - loss: 4.6722e-06 - accuracy: 1.0000
Epoch 85/150
367/367 [==============================] - 1s 2ms/step - loss: 4.1135e-06 - accuracy: 1.0000
Epoch 86/150
367/367 [==============================] - 1s 2ms/step - loss: 3.6750e-06 - accuracy: 1.0000
Epoch 87/150
367/367 [==============================] - 1s 2ms/step - loss: 3.1320e-06 - accuracy: 1.0000
Epoch 88/150
367/367 [==============================] - 1s 

In [32]:

# evaluate the keras model
_, accuracy = model.evaluate(X_train, y_train)
print('Accuracy: %.2f' % (accuracy*100))

115/115 [==============================] - 0s 1ms/step - loss: 3.8225e-06 - accuracy: 1.0000
Accuracy: 100.00


In [33]:
predictions = model.predict(X_test)
predictions[:10]

array([[1.7087368e-09, 9.9999982e-01, 7.3769679e-09, 1.3336219e-16,
        2.4026500e-10, 4.6997247e-16, 2.6492766e-12, 3.9615213e-09,
        1.3273228e-17],
       [3.2290740e-15, 7.9168931e-14, 1.0000000e+00, 2.1149218e-11,
        2.0666512e-22, 2.0950751e-23, 4.2384801e-18, 9.0308793e-29,
        1.3588356e-17],
       [9.0588136e-17, 5.2090819e-12, 3.1707390e-08, 2.1502376e-04,
        8.6303508e-01, 1.4876071e-08, 9.1791153e-04, 2.1435765e-08,
        4.9057990e-11],
       [4.2635091e-07, 9.9999976e-01, 1.5916039e-12, 6.5705955e-19,
        5.4199845e-17, 8.6912158e-20, 1.8070698e-20, 4.8666220e-25,
        3.2574362e-19],
       [3.1053637e-19, 1.4497108e-16, 1.9005682e-26, 6.8289951e-10,
        1.5442004e-21, 1.0000000e+00, 2.5987189e-27, 4.8877832e-22,
        3.8056888e-10],
       [2.1203308e-14, 8.5121297e-05, 9.9999398e-01, 1.2763224e-14,
        6.4553221e-14, 5.0385804e-19, 2.3337809e-20, 4.2008470e-25,
        5.3648510e-19],
       [1.5298211e-17, 3.0905817e-14, 1.

In [34]:
y_test[:10]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)

In [37]:
model.save('fft_model.h5')

Be sure to save the converted model in the correct folder

In [38]:
!tensorflowjs_converter --input_format keras fft_model.h5 javascript\model_fft_js

2020-11-17 21:37:01.493064: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-11-17 21:37:01.493102: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [137]:
!ls

 Volume in drive C is Windows
 Volume Serial Number is 9497-8F11

 Directory of C:\Users\pedro\Documents\programming\python\tf_fft

11/15/2020  08:34 PM    <DIR>          .
11/15/2020  08:34 PM    <DIR>          ..
11/15/2020  01:26 PM    <DIR>          .ipynb_checkpoints
11/15/2020  01:42 PM    <DIR>          fft_data
11/15/2020  08:31 PM           106,328 fft_model.h5
11/15/2020  01:15 PM    <DIR>          js_model
11/15/2020  08:34 PM           287,004 keras fft.ipynb
11/15/2020  01:14 PM           768,088 model.h5
11/15/2020  01:09 PM                84 one-hot encoding key.txt
               4 File(s)      1,161,504 bytes
               5 Dir(s)  202,190,438,400 bytes free
